config/routes.rb
Rails.application.routes.draw do

  scope module: :public, as: 'public' do
    resources :non_monetary_donations, path: :nepenezni_dary, path_names: { new: 'novy' } do
      member do
        get 'signed'
      end
    end
    resources :campaign_donations, path: :penezni_dary, path_names: { new: 'novy' } do
      member do
        get 'signed'
      end
    end
    resources :crowdfundings, path: :crowdfunding, only: [:index, :show]
  end

  scope ":year", year: /20[1-2][0-9]/, path_names: { new: 'pridat', edit: 'upravit' } do

    resources :bank_accounts
    resources :bank_payments, only: [:show] do
      member do
        post 'pair'
      end
    end

    resources :membership_fees

    resources :non_monetary_donations do
      member do
        get 'upload'
        get 'agreement', path: 'smlouva'
      end
    end
    resources :donations, path: 'dary' do
      member do
        get 'confirmation', path: 'potvrzeni'
        get 'agreement', path: 'smlouva'
        get 'upload'
      end
    end

    resources :payments, path: 'platby'

    resources :accountings

    resources :budgets
    resources :budget_categories
    resources :invoices, path: 'faktury' do
      collection do
        get 'unrecognized', to: 'invoices#unrecognized', path: 'neprirazene'
        get 'unreaded', to: 'invoices#unreaded', path: 'nevytezene'
        get 'unpaid', to: 'invoices#unpaid', path: 'nezaplacene'
        get 'unpaired', to: 'invoices#unpaired', path: 'nezauctovane'
        get 'unapproved', to: 'invoices#unapproved', path: 'neschvalene'
      end
      member do
        get 'approval', path: 'schvaleni'
        get 'pay'
        post 'export_to_fio'
      end
      resources :accountings, only: :index
    end

    resources :organizations, path: 'organizace', only: [:index, :show] do
      resources :donation_form_submissions, only: [:index, :show]
      resources :bank_payments, only: [:index]
      resources :gopay_payments, only: [:index]
      resources :budget_categories, path: 'rozpoctova_kapitola', only: [:index, :new]
      resource :budget, path: 'rozpocet', only: [:show, :edit, :update]
      resources :invoices, path: 'faktury', only: [:index, :new] do
        collection do
          get 'unrecognized', to: 'invoices#unrecognized', path: 'neprirazene'
          get 'unreaded', to: 'invoices#unreaded', path: 'nevytezene'
          get 'unpaid', to: 'invoices#unpaid', path: 'nezaplacene'
          get 'unpaired', to: 'invoices#unpaired', path: 'nezauctovane'
          get 'unapproved', to: 'invoices#unapproved', path: 'neschvalene'
        end
      end
      resources :tags, only: [:index]
      resources :accountings, only: [:index]
      resources :donations, path: 'dary', only: [:index] do
        collection do
          get 'above_limit', path: 'nad_limit'
          get 'crowdfunding'
        end
      end
      resources :membership_fees, path: 'clenske_prispevky', only: [:index] do
        collection do
          get 'distribution'
        end
      end
    end

    # scope "/years/:year", as: 'year' do
    #   resources :organizations, only: [:index, :show] do
    #     resources :bank_payments, only: [:index]
    #     resources :gopay_payments, only: [:index]
    #     resources :budget_categories, only: [:index]
    #     resources :invoices, only: [:index, :new]
    #     resources :tags, only: [:index]
    #     resources :accountings, only: [:index]
    #     resources :donations, only: [:index] do
    #       collection do
    #         get 'above_limit'
    #       end
    #     end
    #     resources :membership_fees, only: [:index] do
    #       collection do
    #         get 'distribution'
    #       end
    #     end
    #   end
    # end

    get 'static_pages/index'
    get '/prehled', to: 'static_pages#overview'

    get 'bank_payments', controller: :bank_payments, action: :index
    get 'supporter_fees', controller: :supporter_fees, action: :index

    # resources :books
    # root 'static_pages#index'

    get "/", to: 'static_pages#index', as: :dashboard
  end

  resources :invoices, path: 'faktury'
  resources :people, only: [:show]

  namespace :api do
    resources :bank_payments, only: :index
  end

  resources 'donation_form_submissions', only: [:create]

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'static_pages#index'
  get '/zprava', to: 'static_pages#campaign_report', as: :campaign_report

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_before_filter :authenticate_person!

  def index
  end

  def overview
		@bank_payments = BankPayment.includes(:payments).where("paid_on >= ? AND paid_on <= ?", "#{@year}-01-01", "#{@year}-12-31")
		@bank_payments = @bank_payments.reject{|p| p.remaining_amount == 0}
		@bank_payments = @bank_payments.reject{|p| p.returning_payment || p.returned_payment}
		@unpaired_invoices_balance = Invoice.includes(:payments, :accountings).reject{|p|
				p.payment_remainder == 0}.reject{|p|
				p.accountings.first.try(:budget_category).try(:year)!=@year
			}.inject(0){|t,p| t+=p.payment_remainder}
		@budget_current_balance = Budget.current_balance(@year)
		@unpaired_payments_balance = @bank_payments.inject(0){|t,b| t+=b.amount}
		@bank_accounts_balance = BankAccount.balance
  end

  def campaign_report
    respond_to do |format|
      format.html
      format.pdf {
        pdf = CampaignReportPdf.new()
        send_data pdf.render,
                  filename: "svobodni_zprava_o_financovani_volebni_kampane.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      }
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<h1>Finance Svobodní</h1>
<!--
<h2>Nahlášení nepěněžního plnění</h2>
<%= link_to "Nový dar", new_public_non_monetary_donation_path(), class: "btn btn-default" %>
-->
<h2>Interní systém pro ekonomickou evidenci republiky a krajů.</h2>

<% unless current_user %>
<h2>Prosím, <a href="/auth/registr">přihlašte se</a>.</h2>
<% else %>
<% if [2804,342,7873].member?(current_user['id']) %>
<% @invoices = Invoice.where('created_at > "2017-12-31"').reject{|p| p.payment_remainder == 0} %>
<h2>Nezaplacené faktury</h2>
<table id="invoices" class="table table-striped">
  <thead>
    <tr>
      <th>Datum vložení</th>
      <th>Organizace</th>
      <th>Částka</th>
      <th>K úhradě</th>
      <th>Popis</th>
      <th>Akce</th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.reverse.each do |invoice| %>
      <tr>
        <td data-order="<%=invoice.created_at%>">Před <%= time_ago_in_words(invoice.created_at) %></td>
        <td><%= invoice.organization.try(:name) %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.payment_remainder  %></td>
        <td><%= link_to invoice.description.blank? ? "- bez popisu -" : invoice.description, invoice %></td>
        <td><%= link_to("Zaplatit", pay_invoice_path(invoice), class: "btn btn-xs btn-info") if invoice.is_exportable? if can?(:pay, invoice)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<div class="row">
  <div class="col-md-6">
    <h3>Období</h3>
    <ul>
      <% @years.each do |year| %>
        <li><%=link_to_unless_current year, dashboard_path(year: year) %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-6">
    <h3>Organizace</h3>
    <ul>
      <% @organizations.each do |organization| %>
        <li><%= link_to organization.name, organization %><!--#organization_budget_categories_path(organization, year: Date.today.year) --></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/static_pages/overview.html.erb
<table class="table table-bordered">
	<tbody>
		<tr><th><%= link_to "Stav rozpočtů", budgets_path %>:</th><td class="text-right"><%= number_to_currency @budget_current_balance %></td></tr>
		<tr><th><%= link_to "Nezaplacené faktury", unpaid_invoices_path %>:</th><td class="text-right"><%= number_to_currency @unpaired_invoices_balance %>
		<tr><th><%= link_to "Nespárované platby", bank_payments_path(only: :unpaired) %>:</th><td class="text-right"><%= number_to_currency @unpaired_payments_balance %></td></tr>
		<tr><th>Celkem:</th><td class="text-right"><%= number_to_currency(@budget_current_balance+@unpaired_invoices_balance+@unpaired_payments_balance) %></td></tr>
		<tr><th><%= link_to "Stav účtů", bank_accounts_path %>:</th><td class="text-right"><%= number_to_currency @bank_accounts_balance %></td></tr>
		<tr><th>Rozdíl:</th><td class="text-right"><%= number_to_currency(@budget_current_balance+@unpaired_invoices_balance+@unpaired_payments_balance-@bank_accounts_balance)%></td></tr>
	</tbody>
</table>