config/routes.rb
Rails.application.routes.draw do

  scope module: :public, as: 'public' do
    resources :non_monetary_donations, path: :nepenezni_dary, path_names: { new: 'novy' } do
      member do
        get 'signed'
      end
    end
    resources :campaign_donations, path: :penezni_dary, path_names: { new: 'novy' } do
      member do
        get 'signed'
      end
    end
    resources :crowdfundings, path: :crowdfunding, only: [:index, :show]
  end

  scope ":year", year: /20[1-2][0-9]/, path_names: { new: 'pridat', edit: 'upravit' } do

    resources :bank_accounts
    resources :bank_payments, only: [:show] do
      member do
        post 'pair'
      end
    end

    resources :membership_fees

    resources :non_monetary_donations do
      member do
        get 'upload'
        get 'agreement', path: 'smlouva'
      end
    end
    resources :donations, path: 'dary' do
      member do
        get 'confirmation', path: 'potvrzeni'
        get 'agreement', path: 'smlouva'
        get 'upload'
      end
    end

    resources :payments, path: 'platby'

    resources :accountings

    resources :budgets
    resources :budget_categories
    resources :invoices, path: 'faktury' do
      collection do
        get 'unrecognized', to: 'invoices#unrecognized', path: 'neprirazene'
        get 'unreaded', to: 'invoices#unreaded', path: 'nevytezene'
        get 'unpaid', to: 'invoices#unpaid', path: 'nezaplacene'
        get 'unpaired', to: 'invoices#unpaired', path: 'nezauctovane'
        get 'unapproved', to: 'invoices#unapproved', path: 'neschvalene'
      end
      member do
        get 'approval', path: 'schvaleni'
        get 'pay'
        post 'export_to_fio'
      end
      resources :accountings, only: :index
    end

    resources :organizations, path: 'organizace', only: [:index, :show] do
      resources :donation_form_submissions, only: [:index, :show]
      resources :bank_payments, only: [:index]
      resources :gopay_payments, only: [:index]
      resources :budget_categories, path: 'rozpoctova_kapitola', only: [:index, :new]
      resource :budget, path: 'rozpocet', only: [:show, :edit, :update]
      resources :invoices, path: 'faktury', only: [:index, :new] do
        collection do
          get 'unrecognized', to: 'invoices#unrecognized', path: 'neprirazene'
          get 'unreaded', to: 'invoices#unreaded', path: 'nevytezene'
          get 'unpaid', to: 'invoices#unpaid', path: 'nezaplacene'
          get 'unpaired', to: 'invoices#unpaired', path: 'nezauctovane'
          get 'unapproved', to: 'invoices#unapproved', path: 'neschvalene'
        end
      end
      resources :tags, only: [:index]
      resources :accountings, only: [:index]
      resources :donations, path: 'dary', only: [:index] do
        collection do
          get 'above_limit', path: 'nad_limit'
          get 'crowdfunding'
        end
      end
      resources :membership_fees, path: 'clenske_prispevky', only: [:index] do
        collection do
          get 'distribution'
        end
      end
    end

    # scope "/years/:year", as: 'year' do
    #   resources :organizations, only: [:index, :show] do
    #     resources :bank_payments, only: [:index]
    #     resources :gopay_payments, only: [:index]
    #     resources :budget_categories, only: [:index]
    #     resources :invoices, only: [:index, :new]
    #     resources :tags, only: [:index]
    #     resources :accountings, only: [:index]
    #     resources :donations, only: [:index] do
    #       collection do
    #         get 'above_limit'
    #       end
    #     end
    #     resources :membership_fees, only: [:index] do
    #       collection do
    #         get 'distribution'
    #       end
    #     end
    #   end
    # end

    get 'static_pages/index'
    get '/prehled', to: 'static_pages#overview'

    get 'bank_payments', controller: :bank_payments, action: :index
    get 'supporter_fees', controller: :supporter_fees, action: :index

    # resources :books
    # root 'static_pages#index'

    get "/", to: 'static_pages#index', as: :dashboard
  end

  resources :invoices, path: 'faktury'
  resources :people, only: [:show]

  namespace :api do
    resources :bank_payments, only: :index
  end

  resources 'donation_form_submissions', only: [:create]

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'static_pages#index'
  get '/zprava', to: 'static_pages#campaign_report', as: :campaign_report

end

app/models/donation.rb
class Donation < ActiveRecord::Base

  belongs_to :organization
  has_many :accountings, as: :accountable
  has_many :payments, as: :payable
  before_create :set_accounting
  before_create :set_access_token
  after_create :set_vs

  attr_accessor :bank_payment_id, :budget_category_id, :vs_prefix

  has_attached_file :agreement, path: ":rails_root/data/donation_agreements/:id.pdf", url: "/darovaci-smlouvy/:id.pdf"
  validates_attachment :agreement, content_type: { content_type: ["application/pdf"], message: "musí být PDF" }

  validates :amount, presence: true
  # validates :description, presence: true
  validates :donor_type, presence: true
  # validates :person_id
  validates :name, presence: true
  validates :ic, presence: true, if: :juristic?
  validates :date_of_birth, presence: true, unless: :juristic?
  validates :street, presence: true
  validates :city, presence: true
  validates :zip, presence: true
  validates :email, presence: true

  extend FriendlyId
  friendly_id :access_token

  def monetary?
    true
  end

  def address
    "#{street}, #{zip} #{city}"
  end

  def date_of_birth
    begin
      Date.parse(super.to_s)
    rescue
      super
    end
  end

  def juristic?
    donor_type == "juristic"
  end

  def number
    "#{received_on.year}#{organization.id.to_s.rjust(2,'0')}#{id.to_s.rjust(3,'0')}"
  end

  def payment_received_on
    received_on
  end

  def agreement_received_on
    @agreement_received_on = agreement_updated_at
  end

  def needs_agreement?
    amount > 1000
  end

  def set_accounting
    if received_on > Date.parse("2020-12-31")
      if organization_id==100
        self.accountings.build(budget_category_id: 554, amount: amount)
      else
        self.accountings.build(budget_category_id: self.organization.budgets.where(year:2021).first.donation_budget_category_id, amount: amount)
      end
    elsif received_on > Date.parse("2019-12-31")
      if organization_id==100
        self.accountings.build(budget_category_id: 456, amount: amount)
      else
        self.accountings.build(budget_category_id: self.organization.budgets.where(year:2020).first.donation_budget_category_id, amount: amount)
      end
    elsif received_on > Date.parse("2018-12-31")
      if organization_id==100
        self.accountings.build(budget_category_id: 372, amount: amount)
      else
        self.accountings.build(budget_category_id: self.organization.budgets.where(year:2019).first.donation_budget_category_id, amount: amount)
      end
    elsif received_on > Date.parse("2017-12-31")
      if organization_id==100
        self.accountings.build(budget_category_id: 263, amount: amount)
      else
        self.accountings.build(budget_category_id: self.organization.budgets.where(year:2018).first.donation_budget_category_id, amount: amount)
      end
    elsif received_on > Date.parse("2016-12-31")
      if organization_id==100
        self.accountings.build(budget_category_id: 166, amount: amount)
      else
        self.accountings.build(budget_category_id: self.organization.budgets.where(year:2017).first.donation_budget_category_id, amount: amount)
      end
    elsif received_on > Date.parse("2015-12-31")
      self.accountings.build(budget_category_id: 50, amount: amount) if organization_id==100
    elsif received_on > Date.parse("2014-12-31")
      self.accountings.build(budget_category_id: 11, amount: amount) if organization_id==100
    end if accountings.empty? && received_on
  end

  private
  def set_access_token
    self.access_token = SecureRandom.hex
  end

  def set_vs
    self.update_attribute :vs, "#{self.vs_prefix}#{self.id.to_s.rjust(6,'0')}" if self.vs.blank?
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy, :confirmation, :agreement, :upload]
  respond_to :pdf, only: [:confirmation, :agreement]

  # GET /donations
  # GET /donations.json
  def index
    @donations = @organization ? @organization.donations : Donation.all
    @donations = @donations.includes(accountings:[accountable: [payments: :payment]])
    @donations = @donations.accessible_by(current_ability)

    # if params[:year]
    #   @donations = @donations.where("received_on >= ? AND received_on <= ?", "#{params[:year]}-01-01", "#{params[:year]}-12-31")
    # end

    respond_to do |format|
      format.html {
        @donations = @donations.order(created_at: :desc).page params[:page]
      }
      format.xlsx
    end
  end

  def above_limit
    # @organization = Organization.find_by_id(params[:organization_id])
    if @organization && @organization.id != 100
      @donations = @organization.donations
    else
      @donations = Donation.all
    end
    if params[:limit]
      @donations = @donations.where("amount > ?", params[:limit])
    else
      @donations = @donations.where("amount > 1000")
    end
    @donations = @donations.accessible_by(current_ability)
    @donations = @donations.order(created_at: :desc).page params[:page]
    render action: :index
  end

  def crowdfunding
    @donations = Donation.where("vs like '99%' and LENGTH(vs)=10")
    @donations = @donations.accessible_by(current_ability)
    @donations = @donations.order(created_at: :desc).page params[:page]
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    authorize! :read, @donation
  end

  # GET /donations/new
  def new
    @donation = Donation.new(
      organization: @organization,
      amount: params[:amount],
      bank_payment_id: params[:bank_payment_id],
      budget_category_id: 4,
      person_id: params[:vs] ? params[:vs].reverse[0..3].reverse.to_i : nil
    )
    authorize! :create, @donation
  end

  # GET /donations/1/edit
  def edit
    authorize! :update, @donation
  end

  # POST /donations
  # POST /donations.json
  def create
    @bank_payment = BankPayment.find(params[:donation][:bank_payment_id])
    @donation = Donation.new(donation_params)
    @donation.payments.build(payment: @bank_payment)
    @donation.payments.first.amount = params[:donation][:amount]
    @donation.received_on = @bank_payment.paid_on
    #@donation.accountings.build(budget_category_id: params[:donation][:budget_category_id])
    #@donation.accountings.first.amount = params[:donation][:amount]
    authorize! :create, @donation

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    authorize! :update, @donation
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    authorize! :destroy, @donation
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirmation
    authorize! :read, @donation
    respond_to do |format|
      format.pdf {}
    end
  end

  def agreement
    authorize! :read, @donation
    respond_to do |format|
      format.pdf do
        pdf = DonationAgreementPdf.new(@donation)
        send_data pdf.render,
                  filename: "svobodni_smlouva_#{@donation.id}.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.friendly.find(params[:id])
      @organization = @donation.organization
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:organization_id, :amount, :donor_type, :person_id, :name, :ic, :date_of_birth, :street, :city, :zip, :email, :agreement)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= simple_form_for(@donation, html: { class: 'form-horizontal' }) do |f| %>

  <%= f.error_notification %>
  <%= f.hidden_field :bank_payment_id %>
  <%= f.hidden_field :budget_category_id %>
  <%= f.input :organization_id, collection: @organizations%>
  <%= f.input :amount %>
  <%= f.input :donor_type, collection: {"Osoba" => :natural, "Firma" => :juristic}, include_blank: false %>
  <%= f.input :person_id, hint: "Vložte ID osoby a klikněte pro načtení údajů z registru", wrapper: :horizontal_input_group do %>

    <%= f.input_field :person_id, class: "form-control" %>
    <span class="input-group-addon"><a href="#" id="load_person">Načíst z registru</a></span>
  <% end %>

  <%= f.input :name %>
  <%= f.input :ic %>
  <%= f.input :date_of_birth %>
  <%= f.input :street %>
  <%= f.input :city %>
  <%= f.input :zip %>
  <%= f.input :email %>
  <%= f.button :submit, class: "btn-primary pull-right" %>
<% end %>

<script>
$( 'form' ).on( 'click', '#load_person' , function( event ) {
     console.log("Clicked")
    // set ID
    var person_id = $('#donation_person_id').val();
    // get record
    $.ajax({
        type: 'GET',
        url: '<%="#{configatron.registry.uri}"%>/people/'+person_id+'/private.json',
        dataType: 'json',
        beforeSend: function (xhr) {
          xhr.setRequestHeader("Authorization", "Bearer <%=current_user['access_token']%>")
        },
        success: function ( data ) {
            // display dialog
            var person = data.person
            console.log(person)
            $( '#donation_person_id' ).val( person.id );
            $( '#donation_name' ).val( person.name );
            $( '#donation_donor_type' ).val( 'natural' );
            $( '#donation_date_of_birth' ).val( person.date_of_birth );
            $( '#donation_email' ).val( person.email );
            $( '#donation_street' ).val( person.street );
            $( '#donation_city' ).val( person.city );
            $( '#donation_zip' ).val( person.zip );
        }
    })
})
</script>

app/views/donations/crowdfunding.html.erb
<% page_title "Crowdfunding" %>

<div class="pull-right"><%= paginate @donations %></div>

<table id="donations" class="table table-striped">
  <thead>
    <tr>
      <th>ID daru</th>
      <th>Částka</th>
      <th>Dárce</th>
      <th>Email</th>
      <th>Platba</th>
      <th>Smlouva</th>
      <th>Účel</th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= link_to donation.id, donation %></td>
        <td align="right"><%= number_to_currency donation.amount %></td>
        <td><%= donation.name %></td>
        <td><%= donation.email %></td>
        <td><%= donation.received_on ? donation.received_on : "NE" %></td>
        <td><%= donation.agreement_received_on ? l(donation.agreement_received_on.to_date) : "NE" %></td>
        <td><%= Crowdfunding.find_by(vs_prefix: donation.vs[0..3]).try(:title) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pull-right"><%= paginate @donations %></div>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<% page_title "Přijaté dary" %>

<div class="pull-right"><%= paginate @donations %></div>

<table id="donations" class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Datum</th>
      <th>Částka</th>
      <th>Dárce</th>
      <th>Adresa</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= link_to donation.id, donation %></td>
        <td><%= l donation.received_on %></td>
        <td><%= donation.amount %></td>
        <td><%= donation.name %></td>
        <td><%= donation.address %></td>
        <td>
        <% if donation.agreement_received_on %>
          <%= link_to 'Podepsaná smlouva', signed_public_campaign_donation_path(donation, format: :pdf), class: "btn btn-xs btn-success" %>
        <% else %>
          <%= link_to 'Potvrzení', confirmation_donation_path(donation, format: :pdf), class: "btn btn-xs btn-default" %>
          <%= link_to 'Smlouva', agreement_donation_path(donation, format: :pdf), class: "btn btn-xs btn-default" %>
          <%= link_to 'Nahrát smlouvu', upload_donation_path(donation), class: "btn btn-xs btn-default" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pull-right"><%= paginate @donations %></div>

<%= link_to "Export xlsx", {format: :xlsx}, class: "btn btn-primary" %>

app/views/donations/new.html.erb
<% page_title "Nový dar" %>

<%= render 'form' %>

app/views/donations/show.html.erb
<% page_title "Přijatý dar" %>

<div class="jumbotrons">
  <h2><small><%= @donation.organization.try(:name) %>: </small>
      <%= @donation.name %></h2>
  <p><%#= link_to "Zobrazit PDF", @invoice.document.url, class: "btn btn-default" %></p>
</div>

<div class="row">
  <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Detaily daru</h2>
      </div>
      <div class="panel-body">
        <table class="table">
          <tr><th>Částka:</th><td><%= @donation.amount %></td></tr>
          <tr><th>Jméno:</th><td><%= @donation.name %></td></tr>
          <% unless @donation.ic.blank? %>
          <tr><th>IČ:</th><td><%= @donation.ic %></td></tr>
          <% end %>
          <% unless @donation.date_of_birth.blank? %>
          <tr><th>Datum narození:</th><td><%=l(@donation.date_of_birth)%></td></tr>
          <% end %>
          <tr><th>Ulice:</th><td><%= @donation.street %></td></tr>
          <tr><th>Město:</th><td><%= @donation.city %></td></tr>
          <tr><th>PSČ:</th><td><%= @donation.zip %></td></tr>
          <% unless @donation.email.blank? %>
          <tr><th>Email:</th><td><%= @donation.email %></td></tr>
          <% end %>
        </table>
       <%= link_to 'Upravit', edit_donation_path(@donation), class: "btn btn-default" %>
       <%= link_to 'Potvrzení', confirmation_donation_path(@donation, format: :pdf), class: "btn btn-default" %>
       <%= link_to 'Smlouva', agreement_donation_path(@donation, format: :pdf), class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Úhrada</h2>
      </div>
      <div class="panel-body">
        <table class="table">
        <thead>
          <tr><th>Datum úhrady</th><th>Částka</th></tr>
        </thead>
        <tbody>
          <% for payment in @donation.payments %>
          <tr><td><%= link_to payment.payment.paid_on, payment %></td><td><%= payment.    amount %></td></tr>
          <% end %>
        <tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Zaúčtování v rozpočtu</h2>
      </div>
      <div class="panel-body">
        <table class="table">
        <thead>
          <tr><th>Kategorie</th><th>Částka</th></tr>
        </thead>
        <tbody>
          <% for accounting in @donation.accountings %>
          <tr><td><%= link_to accounting.budget_category.name, accounting.    budget_category if accounting.budget_category %><br/><%= accounting.    tag_list %></td><td><%= accounting.amount %></td><td><%= link_to "Upravit",     edit_accounting_path(accounting) %></td></tr>
          <% end %>
        <tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/donations/upload.html.erb
<% unless @donation.agreement_received_on %>
<a name="nahrat"></a>
<div class="panel panel-info">
  <div class="panel-heading">
    <h2>Nahrání naskenované podepsané smlouvy</h2>
  </div>
  <div class="panel-body">
    <%= simple_form_for(@donation,  html: { class: 'form-horizontal' }) do |f| %>
      <%= f.input :id, disabled: true %>
      <%= f.input :name, disabled: true %>
      <%= f.input :amount, disabled: true %>
      <%= f.input :agreement, label: "PDF soubor se smlouvou" %>
      <%= f.button :submit, "Uložit smlouvu", class: "btn-primary pull-right" %>
    <% end %>
  </div>
</div>
<% end %>