config/routes.rb
Rails.application.routes.draw do

  scope module: :public, as: 'public' do
    resources :non_monetary_donations, path: :nepenezni_dary, path_names: { new: 'novy' } do
      member do
        get 'signed'
      end
    end
    resources :campaign_donations, path: :penezni_dary, path_names: { new: 'novy' } do
      member do
        get 'signed'
      end
    end
    resources :crowdfundings, path: :crowdfunding, only: [:index, :show]
  end

  scope ":year", year: /20[1-2][0-9]/, path_names: { new: 'pridat', edit: 'upravit' } do

    resources :bank_accounts
    resources :bank_payments, only: [:show] do
      member do
        post 'pair'
      end
    end

    resources :membership_fees

    resources :non_monetary_donations do
      member do
        get 'upload'
        get 'agreement', path: 'smlouva'
      end
    end
    resources :donations, path: 'dary' do
      member do
        get 'confirmation', path: 'potvrzeni'
        get 'agreement', path: 'smlouva'
        get 'upload'
      end
    end

    resources :payments, path: 'platby'

    resources :accountings

    resources :budgets
    resources :budget_categories
    resources :invoices, path: 'faktury' do
      collection do
        get 'unrecognized', to: 'invoices#unrecognized', path: 'neprirazene'
        get 'unreaded', to: 'invoices#unreaded', path: 'nevytezene'
        get 'unpaid', to: 'invoices#unpaid', path: 'nezaplacene'
        get 'unpaired', to: 'invoices#unpaired', path: 'nezauctovane'
        get 'unapproved', to: 'invoices#unapproved', path: 'neschvalene'
      end
      member do
        get 'approval', path: 'schvaleni'
        get 'pay'
        post 'export_to_fio'
      end
      resources :accountings, only: :index
    end

    resources :organizations, path: 'organizace', only: [:index, :show] do
      resources :donation_form_submissions, only: [:index, :show]
      resources :bank_payments, only: [:index]
      resources :gopay_payments, only: [:index]
      resources :budget_categories, path: 'rozpoctova_kapitola', only: [:index, :new]
      resource :budget, path: 'rozpocet', only: [:show, :edit, :update]
      resources :invoices, path: 'faktury', only: [:index, :new] do
        collection do
          get 'unrecognized', to: 'invoices#unrecognized', path: 'neprirazene'
          get 'unreaded', to: 'invoices#unreaded', path: 'nevytezene'
          get 'unpaid', to: 'invoices#unpaid', path: 'nezaplacene'
          get 'unpaired', to: 'invoices#unpaired', path: 'nezauctovane'
          get 'unapproved', to: 'invoices#unapproved', path: 'neschvalene'
        end
      end
      resources :tags, only: [:index]
      resources :accountings, only: [:index]
      resources :donations, path: 'dary', only: [:index] do
        collection do
          get 'above_limit', path: 'nad_limit'
          get 'crowdfunding'
        end
      end
      resources :membership_fees, path: 'clenske_prispevky', only: [:index] do
        collection do
          get 'distribution'
        end
      end
    end

    # scope "/years/:year", as: 'year' do
    #   resources :organizations, only: [:index, :show] do
    #     resources :bank_payments, only: [:index]
    #     resources :gopay_payments, only: [:index]
    #     resources :budget_categories, only: [:index]
    #     resources :invoices, only: [:index, :new]
    #     resources :tags, only: [:index]
    #     resources :accountings, only: [:index]
    #     resources :donations, only: [:index] do
    #       collection do
    #         get 'above_limit'
    #       end
    #     end
    #     resources :membership_fees, only: [:index] do
    #       collection do
    #         get 'distribution'
    #       end
    #     end
    #   end
    # end

    get 'static_pages/index'
    get '/prehled', to: 'static_pages#overview'

    get 'bank_payments', controller: :bank_payments, action: :index
    get 'supporter_fees', controller: :supporter_fees, action: :index

    # resources :books
    # root 'static_pages#index'

    get "/", to: 'static_pages#index', as: :dashboard
  end

  resources :invoices, path: 'faktury'
  resources :people, only: [:show]

  namespace :api do
    resources :bank_payments, only: :index
  end

  resources 'donation_form_submissions', only: [:create]

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'static_pages#index'
  get '/zprava', to: 'static_pages#campaign_report', as: :campaign_report

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base

  validates :name, presence: true
  validates :description, presence: true
  validates :account_type, presence: true
  validates :account_number, presence: true, format: { with: /\A[0-9\-]{2,20}\z/ }
  validates :bank_code, presence: true, format: { with: /\A[0-9]{4}\z/ }

  has_many :payments, class_name: "BankPayment", foreign_key: :our_account_number, primary_key: :account_number

  def full_account_number
    [account_number, bank_code].join('/')
  end

  def our_full_account_number
    [our_account_number, our_bank_code].join('/')
  end

  def self.account_types
    # http://www.zakonyprolidi.cz/cs/1991-424#p17a-2
    {
      "příspěvky ze státního rozpočtu, příjmy z darů a jiných bezúplatných plnění" => 1,
      "plnění vyplývající z pracovněprávního vztahu ke straně a hnutí a politickému institutu" => 2,
      "financování volebních kampaní za podmínek stanovených volebními zákony" => 3,
      "ostatní příjmy a výdaje" => 4
    }
  end

  def import
    FioAPI.token = token
    list = FioAPI::List.new
    list.from_last_fetch
    response = list.response
    account = response.account
    update_attribute :balance, account.closing_balance
    response.transactions.each { |transaction|
      BankPayment.create!(
        amount: transaction.amount,
        paid_on: Date.parse(transaction.date),
        currency: transaction.currency,
        transaction_id: transaction.transaction_id,  # 13850125596
        account_number: transaction.account,
        account_name: transaction.account_name,
        bank_code: transaction.bank_code,
        vs: transaction.vs || '',
        ks: transaction.ks || '',
        ss: transaction.ss || '',
        info: transaction.message_for_recipient || '',
        our_account_number: account.account_id,
        our_bank_code: account.bank_id,
      ) unless BankPayment.find_by_transaction_id_and_our_account_number(transaction.transaction_id,account.account_id)
    }
  end

  def self.balance
    all.sum(:balance)
  end

end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_organization
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.accessible_by(current_ability).all
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
    @bank_payments=@bank_account.payments.accessible_by(current_ability).order(created_at: :desc).page params[:page]
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
    authorize! :create, @bank_account
  end

  # GET /bank_accounts/1/edit
  def edit
    authorize! :update, @bank_account
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)
    authorize! :create, @bank_account
    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to bank_accounts_path, notice: 'Nový bankovní účet byl úspěšně uložen.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    authorize! :update, @bank_account
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to bank_accounts_path, notice: 'Bankovní účet byl úspěšně uložen.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    def set_organization
      @organization = Organization.find(100)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:name, :description, :account_type, :account_number, :bank_code, :balance, :token)
    end
end

app/views/bank_accounts/_form.html.erb
<%= simple_form_for(@bank_account, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :account_type, collection: BankAccount.account_types %>
  <%= f.input :account_number %>
  <%= f.input :bank_code %>
  <%= f.button :submit, class: "btn-primary pull-right" %>
<% end %>

app/views/bank_accounts/edit.html.erb
<% page_title "Úprava údajů bankovního účtu" %>

<%= render 'form' %>

app/views/bank_accounts/index.html.erb
<% page_title 'Stav bankovních účtů' %>

<%= link_to ' + Přidat nový bankovní účet', new_bank_account_path, class: "btn btn-xs btn-primary pull-right"  %>

<table class="table table-stripped">
  <thead>
    <tr>
      <th><%=t("activerecord.attributes.bank_account.name")%></th>
      <th><%=t("activerecord.attributes.bank_account.account_number")%></th>
      <th><%=t("activerecord.attributes.bank_account.balance")%></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% total = 0%>
    <% @bank_accounts.each do |bank_account| %>
      <% total += bank_account.balance %>
      <tr>
        <td><%= bank_account.name %></td>
        <td><%= bank_account.full_account_number %></td>
        <td><%= number_to_currency(bank_account.balance) %></td>
        <td class="text-right">
          <%= link_to 'Zobrazit pohyby', bank_account_path(bank_account), class: "btn btn-xs btn-primary" %> |
          <%= link_to 'Upravit', edit_bank_account_path(bank_account), class: "btn btn-xs btn-warning" %> |
          <% if @year %>
          <%= link_to 'FIO', "https://www.fio.cz/ib2/transparent?a=#{bank_account.account_number}&f=01.01.#{@year}&t=31.12.#{@year}", class: "btn btn-xs btn-info" %>
          <% else %>
          <%= link_to 'FIO', "https://www.fio.cz/ib2/transparent?a=#{bank_account.account_number}", class: "btn btn-xs btn-info" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <th>CELKEM</th>
      <th></th>
      <th><%= number_to_currency(total) %></th>
    </tr>
  </tbody>
</table>

<br>

app/views/bank_accounts/new.html.erb
<% page_title 'Nový účet v bance' %>

<%= render 'form' %>

app/views/bank_accounts/show.html.erb
<% page_title "Pohyby na bankovním účtu #{@bank_account.full_account_number} - #{@bank_account.name}" %>

<div class="pull-right"><%= paginate @bank_payments %></div>

<table class="table table-stripped">
  <thead>
    <tr>
      <th><%=t("activerecord.attributes.bank_payment.paid_on")%></th>
      <th><%=t("activerecord.attributes.bank_payment.vs")%></th>
      <th><%=t("activerecord.attributes.bank_payment.amount")%></th>
      <th><%=t("activerecord.attributes.bank_payment.account_name")%></th>
      <th><%=t("activerecord.attributes.bank_payment.info")%></th>
      <th></th>
    </tr>

  </thead>
  <tbody>
  <% @bank_payments.each do |payment| %>
    <tr>
      <td><%=l payment.paid_on%></td>
      <td><%=link_to_registry_person payment.vs%></td>
      <td><%=payment.amount%></td>
      <td><%=payment.account_name%></td>
      <td><%=highlight(payment.info, %w(dar prispevek příspěvek))%></td>
      <td>
        <% if payment.returning_payment %>
          <span class="label label-info">Vráceno</span>
        <% elsif payment.returned_payment %>
          <span class="label label-info">Vratka</span>
        <% elsif can? :create, Donation.new(organization: @organization)%>
          <%= link_to "Nový dar", new_donation_path(organization_id: @organization, vs: payment.vs, amount: payment.remaining_amount, bank_payment_id: payment.id), class: "btn btn-default btn-xs" if payment.donation_expected? %>
          <%= button_to("Párovat", pair_bank_payment_path(payment), class: "btn btn-danger btn-xs") if payment.remaining_amount>0 %>
        <% end %>
        <%=link_to "Detail", payment, class: "btn btn-primary btn-xs" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="pull-right"><%= paginate @bank_payments %></div>